# Jekyll Config
url: "https://yokim05-snu-eng.github.io"
baseurl: "/"
permalink: pretty
title: "김영오 홈페이지"
collections_dir: collections
markdown: kramdown
highlighter: rouge

sass:
  indentWidth: 4
  style: compact
  precision: 10

collections:
  posts:
    output: false

defaults:
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

# Theme Config
# google_analytics_id: "G-YB8SKVCHYJ"
enable_dark_mode: false
enable_fixed_header: true

colors:
  primary: "#20509e"
  secondary: "#ff9c07"

fonts:
  google_fonts: "https://fonts.googleapis.com/css2?family=Lora&family=Fira+Mono&family=Source+Sans+Pro:wght@300;400;600&display=swap"
  heading: "Source Sans Pro"
  base: "Source Sans Pro"
  monospace: "Fira Mono"

logo:
  logo: assets/2026/images/snu-engineering-logo.svg
  logo_mobile: assets/2026/images/snu-engineering-logo.svg
  logo_invert: assets/2026/images/snu-engineering-logo.svg
  logo_invert_mobile: assets/2026/images/snu-engineering-logo.svg
  logo_desktop_height: "40px"
  logo_desktop_width: "auto"
  logo_mobile_height: "32px"
  logo_mobile_width: "auto"

footer:
  enable_contact_details: true
  contact_details_heading: "Contact"

  enable_social_media_icons: false

  enable_menu_footer_primary: true
  footer_primary_menu_title: "Menu"
  enable_menu_footer_secondary: false
  footer_secondary_menu_title: "Vision"
  enable_menu_footer_tertiary: true
  footer_tertiary_menu_title: "&nbsp;"
  enable_bottom_menu: false

  enable_copyright: true
  copyright: "© 2026 김영오 with Claude Code. v2.3.6"

contact:
  show_contact_details: true

enable_sidebar_services: true
enable_breadcrumbs_services: true
enable_sidebar_projects: false
enable_breadcrumbs_projects: true
enable_sidebar_courses: false
enable_breadcrumbs_courses: false

# Plugins Config
plugins:
  - jekyll-environment-variables
  - jekyll-paginate-v2
  - jekyll-sitemap
  # - jekyll-paginate

pagination:
  enabled: false
  debug: false
  collection: "posts"
  per_page: 50
  permalink: "/page/:num/"
  title: ":title - page :num"
  sort_field: "date"
  sort_reverse: true
  trail:
    before: 2
    after: 2
  indexpage: "index"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
